server:
  port: 8080
  servlet:
    context-path:

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.46.15:3306/suit_customization?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: bing6749
  
  # Spring MVC配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.suitcustom.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# JWT配置
jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 86400000

# Swagger配置
swagger:
  enabled: true
  title: 西装定制管理系统接口文档
  description: 西装定制管理系统后端接口文档
  version: 1.0.0
  base-package: com.suitcustom.controller

# 日志配置
logging:
  level:
    com.suitcustom: debug
    org.springframework: warn

# Redis配置
redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 10000
  lettuce:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

# 文件上传配置
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB

# 文件存储路径
file:
  upload-dir: ./uploads/ 